# Generated by Django 4.0.3 on 2022-03-13 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Filmyweb', '0003_film_opis_film_premiera'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='imdb_ratting',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='film',
            name='plakat',
            field=models.ImageField(blank=True, null=True, upload_to='plakaty'),
        ),
    ]
