# Generated by Django 4.0.3 on 2022-03-19 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Filmyweb', '0005_rename_imdb_ratting_film_imdb_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='DodatkoweInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('czas_trwania', models.PositiveSmallIntegerField(default=0)),
                ('gatunek', models.PositiveSmallIntegerField(choices=[(2, 'Akcja'), (4, 'Horror'), (1, 'Komedia'), (5, 'Drama'), (0, 'Inne'), (3, 'Sci-fi')], default=0)),
            ],
        ),
        migrations.AddField(
            model_name='film',
            name='dodatkowe',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Filmyweb.dodatkoweinfo'),
        ),
    ]
